name: Share data between fping jobs

on: [push]

jobs:
 job:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: set up
        shell: bash
        run: |
          sudo apt-get install sipcalc jq dnsutils net-tools
          python3 -m pip install pipenv --user
          python3 -m pip install awscli
          pipenv run aws configure
            ./add-record53.sh --type=CNAME --record=sonarr.beyerautomation.com --value=www.beyerautomation.com --zone=Z2ZDO4FIWQ98BH --profile=dyndns
      - name: Download result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
