name: Share data between fping jobs

on: [push]

jobs:
 job:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: set up
        shell: bash
        run: |
          sudo apt-get install sipcalc jq dnsutils net-tools
          python3 -m venv ./.venv/
          . ./.venv/bin/activate
          pip install -r ./requirements.txt
      - name: Download result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
