name: Share data between fping jobs

on: [push]

jobs:
 job:
    name: Display results
    runs-on: ubuntu-latest
    steps:
      - name: set up
        shell: bash
        run: |
          sudo apt-get install sipcalc jq dnsutils net-tools
          pipenv install
          pipenv sync
          pipenv run aws configure
      - name: Download result for job 1
        uses: actions/download-artifact@v4
        with:
          name: homework_pre
